services:
  app:
    build: .
    restart: always
    env_file: ./deploy/.env
    environment:
      DATABASE_FILE: /app/deploy/database.db
      PORT: 3000
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - type: bind
        source: ./deploy
        target: /app/deploy
        bind:
          create_host_path: true
